service: serverlss-rust-sample
provider:
    name: aws
    runtime: rust
    memorySize: 128
    region: ap-northeast-1

package:
    individually: true

plugins:
    - serverless-rust

functions:
    rust-sls-sample:
        handler: rust-sls-sample